@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NzkxNTY0NTV9.4fOsO5W7DkaFYFm-5PSLAlAmlj47TzoxrP50hTeGwMU

POST http://localhost:3000/cartedproducts.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "product_id": 1,
  "quantity": 4
  }

###

GET http://localhost:3000/cartedproducts.json
Authorization: Bearer {{jwt}}

