@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NzkwNzkyMzF9.qckDiHcGTjs16LazVUtljdXiVubjouOnS9DP-pDoK_E

POST http://localhost:3000/cartedproducts.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "product_id": 2,
  "quantity": 3
  }

###

GET http://localhost:3000/cartedproducts.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

