@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NzkxNTY0NTV9.4fOsO5W7DkaFYFm-5PSLAlAmlj47TzoxrP50hTeGwMU

POST http://localhost:3000/orders.json
Content-Type: application/json

{
  "user_id": 1,
  "product_id": 2,
  "quantity": 2,
  "subtotal": 3,
  "tax": 1,
  "total": 4
}


###

POST http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "quantity": 1,
  "product_id": 1
}



###
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content_type: application/json
