@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2Nzg4MTkwNzR9.6-tzPyZBkTEZU5zX9iwjwEVkqTs4iSOYkbjBP6Nz83E

@jwt_admin = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2Nzg4MTkwNzR9.6-tzPyZBkTEZU5zX9iwjwEVkqTs4iSOYkbjBP6Nz83E

GET http://localhost:3000/products.json

###

POST http://localhost:3000/products.json
Authorization: Bearer {{jwt_admin}}
Content-Type: application/json

{"name": "Carrot",
"price": 4,
"description": "An herbaceous, generally biennial plant of the Apiaceae family that produces an edible taproot.",
"supplier_id": 2
}

###

PATCH http://localhost:3000/products/6.json
Content-Type: application/json

{
  "name": "test update"
  }

###

DELETE http://localhost:3000/products/10.json

###

POST http://localhost:3000/products.json 
