GET http://localhost:3000/products.json

###

POST http://localhost:3000/products.json
Content-Type: application/json

{"name": "Celery",
"price": 3,
"image_url": "https://i.ytimg.com/vi/WC2ZupdKbm0/sddefault.jpg",
"description": "A low calorie vegetable that consists mostly of water, but also provides antioxidants and fiber."}

