POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Buster",
  "email": "Buster@test.com",
  "password": "bark",
  "password_confirmation": "bark"
}


###

POST http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2Nzg4MTE0OTN9.kcEA_EDW6BZiHlRhQhpLTu2-IaSOKdu6sFIyB_ggpiQ
Content-Type: application/json


